### ISSUE TITLE
autocomplete in use statment providing complete function signature instead of only the name in case of an interface

### ISSUE THREAD

**Issue by JHenneberg** [fortran-lang/fortls#150]
Autocomplete in use statment providing complete function signature instead of only the name in case of an interface:

```f90
program main
  use some_mod, only: some_sub(x, y) ! autocomplete should give only `some_sub`
  implicit none
end program main

module some_mod
  implicit none

  private
  public :: some_sub
  interface some_sub
    module procedure a_subroutine
    module procedure b_subroutine
  end interface

contains

  subroutine a_subroutine(x)
    implicit none

    integer, intent(in) :: x

    write(*,*) 'x = ', x
  end subroutine a_subroutine

  subroutine b_subroutine(x, y)
    implicit none

    integer, intent(in) :: x, y

    write(*,*) 'x = ', x
    write(*,*) 'y = ', y
  end subroutine b_subroutine

end module some_mod
```

Probably related to #6 .

**Comment by gnikit** [comment]
This is a known issue/feature, the idea behind it was that since we can't do overloaded interfaces yet at least serve the entire signature snippet for the user to see what the language server is guessing. BTW that is the default behaviour for functions and subroutines too, I just have it disabled by passing the --use-signature-help flag in the default VS Code options.

**Comment by JHenneberg** [comment]
Ok I understand.

**Comment by gnikit** [comment]
Finally got time to look at this, solution was trivial and quite unrelated to the overloading issue. Apologies @JHenneberg for having to wait so long.

**Comment by JHenneberg** [comment]
I am happy that it was an easy fix. Thanks for maintaining this software.
