### ISSUE TITLE
bug(parser): variable types with line continuation character not parsed

### ISSUE THREAD

**Issue by certik** [fortran-lang/fortls#235]
Can't find the symbol "i" if you put the cursor at the last line and press F12 in VSCode
```fortran
program test_ls
implicit none
inte&
&ger &
    :: i
    
i = 5
end program
```
The following works:
```fortran
program test_ls
implicit none
integer &
    :: i
    
i = 5
end program
```

I just tested one of our examples from LFortran. I don't know for sure, but I think you have to have a full Fortran parser to parse everything.

**Comment by gnikit** [comment]
I missed this type of syntax, I actually didn't know this was possible. Even syntax highlighting seems to break when splitting an intrinsic type with `&`. Definitely the LFortran parser is superior in every single aspect. Will try and see if I can patch fortls'.

**Comment by certik** [comment]
This is just a minor example. Why don't you figure out a roadmap how we can use LFortran's parser and semantics for fortls? That way we can slowly work towards it and fix all issues eventually.

**Comment by gnikit** [comment]
Let's continue this conversation in #85

**Comment by gnikit** [comment]
I am not sure if this is possible to fix with the native fortls parser since the REGEX reads something like `r"(INTEGER|REAL|CHARACTER|COMPLEX)"` and we would have to do lookarounds for the `&` character and that will probably impact performance (if at all doable within the current framework).

Just another reason why a compiler parser would do a better job at capturing such edge cases.

I will leave this open for now and see **if and how** some small number of the regular expression can be modified with lookarounds. If the performance difference (I will have to also write some tools to get performance stats) is too great or I can't figure this out in fortls I will mark it as `Won't Fix` and we can use it as a test case for the LFortran's LSP parser test suite.
