### ISSUE TITLE
Subroutine arguments should be autocompleted before the arugment types are defined

### ISSUE THREAD

**Issue by aerosayan** [fortran-lang/fortls#323]
**Is your feature request related to a problem? Please describe.**
Fortran is extremely verbose ... Auto-completion feature is a necessity.

In this code below ...

```fortran
  subroutine foo(nodes, cells)
    implicit none
    real(kind=8), allocatable :: nodes(:, :)     ! <<< BAD: Auto-compleiton for nodes doesn't work in this line
    integer(kind=4), allocatable :: cells(:, :)  ! <<< BAD: Auto-compleiton for cells doesn't work in this line ... but auto-completion for nodes works in this line

    print *, nodes, cells ! <<< GOOD: Auto-completion for both nodes and cells work correctly in this line
  end subroutine
```

We first declare the subroutine arguments `nodes`, and `cells` in the argument list ... but when we try to define the arguments inside the subroutine, we don't get auto-completion support for `nodes` and `cells`. That's bad.

The auto-completion for the two arguments only start working after we've defined them.

Understandably, this happens probably because initially the LSP doesn't have the AST or type information for the arguments, so it doesn't provide auto-completion.

I think it should.

Because without auto-completion for the subroutine arguments, I have to type 5 to 20 arguments manually, since Fortran subroutines take many arguments. Some old Fortran codes take even more arguments.

I have custom snippets to  type `integer(kind=4), allocatable :: ` in two strokes .. so I can automate that easily ... but I can not automate the auto-completion of the arguments `nodes` and `cells`.

**Describe the solution you'd like**
Provide auto-completion for the function arguments even before defining them.

In the line `real(kind=8), allocatable :: ` when I type `no` ... the LSP should suggest auto-completion for `nodes`.

In the line `integer(kind=4), allocatable :: ` when I type `ce` ... the LSP should suggest auto-completion for `cells`.

If fortls needs a full AST before suggesting auto-completion, then you might be able to simulate it, by defining the arguments with a fake type i.e something like `integer :: nodes, cells` in memory, and using that fake AST to suggest auto-completions.

**Describe alternatives you've considered**
Nothing. We have to manually type it.

**Additional context**
I'm using fortls as an LSP for neovim editor. Kindly let me know if more information is required.

Thanks!

**Comment by gnikit** [comment]
The problem is that you can't serve completion results for variables that have not been defined. As you correctly mentioned, you need valid AST nodes to server any LSP results. The parsing (and hence the AST creation) and the fulfilment of completion requests happen at quite different stages so injecting temporary nodes for undefined variables is likely to break the language server across a few places.

I mostly operate under the assumption that if I have to frequently input 20 arguments in a method, then I am doing something wrong. That piece of code is a prime candidate for refactoring IMO.

I don't see us implementing this feature. We are always happy to receive Pull Requests so you can try and implement this feature yourself. I will however point out _a-priori_ that a PR this would only be considered as a candidate if:
- it did not change the behaviour of other LSP requests
- and/or it didn't cause other LSP requests to serve inaccurate information
- and it did not impact performance in a noticeable way.
