### ISSUE TITLE
Modern Fortran VS Code Extension Fortran > Fortls: Configure. The link is broken.

### ISSUE THREAD

**Issue by nickbrady** [fortran-lang/fortls#334]
Modern Fortran VS Code Extension
Fortran > Fortls: Configure
These links are broken.
https://gnikit.github.io/fortls/options.html#configuration-using-a-file 
https://gnikit.github.io/fortls/options.html#configuration-using-the-command-line
Many references to `documentation` direct here: https://gnikit.github.io/fortls/options.html#pp-defs
which is also broken

<img width="742" alt="Screenshot 2023-11-17 at 11 32 47 AM" src="https://github.com/fortran-lang/fortls/assets/7471367/71f1946f-cdc8-422e-b6b9-239bd4d6d587">
<img width="691" alt="Screenshot 2023-11-17 at 11 51 13 AM" src="https://github.com/fortran-lang/fortls/assets/7471367/bb560fee-ee8e-40ea-bf91-5f10b5277c52">
<img width="691" alt="Screenshot 2023-11-17 at 11 51 22 AM" src="https://github.com/fortran-lang/fortls/assets/7471367/abad52f9-a2e7-4f83-b045-9ef8f9bd492c">

**Comment by gnikit** [comment]
This is because we migrated the projects to fortran-lang (from my personal account) and the links have not been updated in the main release. We are waiting for some news to be announced to issue v4.0.0 of Modern Fortran. Until then, you can install and use the pre-release. This is basically what v4.0.0 will look like (minus a couple of improvements)
